### ISSUE TITLE
Error on a clean install...

### ISSUE THREAD

**Issue by ransems** [ActiveForums/ActiveForums#136]
AssemblyVersion:7.2.2
PortalID:-1
PortalName:
UserID:-1
UserName:
ActiveTabID:-1
ActiveTabName:
RawURL:
AbsoluteURL:
AbsoluteURLReferrer:
UserAgent:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:60bdfd81-a451-47f6-8429-de3cafbc7ee1
InnerException:Could not load file or assembly 'DotNetNuke.Modules.ActiveForums' or one of its dependencies. The system cannot find the file specified.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:System.RuntimeTypeHandle.GetTypeByName
StackTrace:
Message:

System.IO.FileNotFoundException: Could not load file or assembly 'DotNetNuke.Modules.ActiveForums' or one of its dependencies. The system cannot find the file specified.
File name: 'DotNetNuke.Modules.ActiveForums'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at DotNetNuke.Services.Scheduling.ProcessGroup.GetSchedulerClient(String strProcess, ScheduleHistoryItem objScheduleHistoryItem)
   at DotNetNuke.Services.Scheduling.ProcessGroup.Run(ScheduleHistoryItem objScheduleHistoryItem)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
##

**Comment by artfuld** [comment]
Sorry for the late answer, have you got this fixed?

**Comment by ransems** [comment]
I did not, gave up and tried another forum mod. Love to see what it can do, but alas that project has been parked. Any thoughts on what was/is causing the issue?

**Comment by artfuld** [comment]
Just looking at the error message it seems like the .dll wasn't installed.
What version of AF was this? A lot has happened since august :).

**Comment by ransems** [comment]
I'll pull down the latest (beta?) and try again.

**Comment by artfuld** [comment]
Yes, please do. And if you still have problem let me know and I'll try to help you sort them out!
