### ISSUE TITLE
Subquery returned more than 1 value

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#157]
I'm reposting this here so we can track what needs corrected.  This issue has randomly popped up on me on more than one forum.  I had originally thought it was a tapatalk issue, but I'm starting to see this more often and have tapatalk disabled on the site I'm seeing it on.  So either it started prior to disabling or it doesn't have anything to do with tapatalk. 

User complains that when viewing the forum there is no content.  Going to search or active topics etc returns results, but the forum main view shows:
![image](https://cloud.githubusercontent.com/assets/6083121/4713369/17a18048-58e0-11e4-9e0a-08be41cd4ba3.png)

When inspecting the event logs I'm seeing the following error from the user in question:

Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:System.Data.SqlClient.SqlConnection.OnError
StackTrace:
Message:
System.Data.SqlClient.SqlException (0x80131904): Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataSet dataSet, String srcTable, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteDataset(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteDataset(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteDataset(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.SqlDataProvider.UI_ForumView(Int32 PortalId, Int32 ModuleId, Int32 UserId, Boolean IsSuper, String ForumIds)
   at DotNetNuke.Modules.ActiveForums.ForumController.GetForumView(Int32 portalId, Int32 moduleId, Int32 currentUserId, Boolean isSuperUser, String forumIds)
   at DotNetNuke.Modules.ActiveForums.Controls.ForumView.BuildForumView(Int32 ForumTemplateId, Int32 CurrentUserId, String ThemePath)
ClientConnectionId:49be287e-a07b-4522-9fe5-74342ba2f330

I have a workaround to correct this on a per user basis, but I would like to determine why this is happening and prevent it instead of fix it.  I'm making a backup of the database and going to investigate. 
##

**Comment by eddycrompton** [comment]
Hi, you mentioned you had a workaround for this - I assume some SQL script ? Could you share please - we have the same problem with a client site.

**Comment by supermansrf** [comment]
Each time I have had to deal with this, I had to get my developer involved.   I'm not 100% sure that this will work because my notes tell me that last time I had to deal with this I had a problem running the first part of the script. So this script may work for you or it may need tweaked a bit.   If you can't figure it out let me know and I will ask him but it may take a few days.  

I have this marked here so we can look into this more.  I don't have a tried and true fix for it yet.  

--Query 1: Check if bad data is present, for any user and forum
combination
SELECT, COUNT(*)
FROM dbo.activeforums_Forums_Tracking
group by ForumId, UserId
having COUNT(*) > 1

--Get Id of records which have bad data
SELECT TrackingId
FROM dbo.activeforums_Forums_Tracking
WHERE ForumId = <from above> AND UserId = <from above>

--Delete culprit record
delete from dbo.activeforums_Forums_Tracking WHERE TrackingId = <>

**Comment by eddycrompton** [comment]
Thanks for that - will give it a try.

On 16 September 2015 at 16:53, Seth Folickman <notifications@github.com>
wrote:

> Each time I have had to deal with this, I had to get my developer
> involved. I'm not 100% sure that this will work because my notes tell me
> that last time I had to deal with this I had a problem running the first
> part of the script. So this script may work for you or it may need tweaked
> a bit. If you can't figure it out let me know and I will ask him but it may
> take a few days.
>
> I have this marked here so we can look into this more. I don't have a
> tried and true fix for it yet.
>
> --Query 1: Check if bad data is present, for any user and forum
> combination
> SELECT, COUNT(
>
>
> *) FROM dbo.activeforums_Forums_Tracking group by ForumId, UserId having
> COUNT(*) > 1
>
> --Get Id of records which have bad data
> SELECT TrackingId
> FROM dbo.activeforums_Forums_Tracking
> WHERE ForumId = AND UserId =
>
> --Delete culprit record
> delete from dbo.activeforums_Forums_Tracking WHERE TrackingId = <>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ActiveForums/ActiveForums/issues/157#issuecomment-140784397>
> .
>



-- 
Regards,
Eddy Crompton

mobile: +44 (0)7967 331005
Skype: glanton.eddy
