### ISSUE TITLE
Upgrade Error - InnerException:ATTACHINSERTALLOWED

### ISSUE THREAD

**Issue by frozendnn** [ActiveForums/ActiveForums#219]
How do I fix this? Using Latest DNN and AF releases. Thanks for your time. 

FORUM URL - Default.aspx?tabid=64&error=ATTACHINSERTALLOWED&content=0

Error message in Event Log-=
AssemblyVersion:7.3.4
PortalID:0
PortalName:
UserID:-1
UserName:
ActiveTabID:64
ActiveTabName:FORUMS
RawURL:/default.aspx?tabid=64&userId=
AbsoluteURL:/default.aspx
AbsoluteURLReferrer:
UserAgent:Mozilla/5.0 (Linux; U; Android 2.2; fr-fr; Desire_A8181 Build/FRF91) App3leWebKit/53.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:ed45de69-bcb1-4cf0-9eab-de7309e87f5e
InnerException:ATTACHINSERTALLOWED
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:System.Data.ProviderBase.FieldNameLookup.GetOrdinal
StackTrace:
Message:
DotNetNuke.Services.Exceptions.ModuleLoadException: ATTACHINSERTALLOWED ---> System.IndexOutOfRangeException: ATTACHINSERTALLOWED
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.LoadSettings(IDataRecord dr)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.Forums_List(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumController.GetForumsForUser(String userRoles, Int32 portalId, Int32 moduleId, String permissionType, Boolean strict)
   at DotNetNuke.Modules.ActiveForums.SettingsBase.get_UserForumsList()
   at DotNetNuke.Modules.ActiveForums.Classic.GetControl(String view, String options)
   --- End of inner exception stack trace ---

**Comment by artfuld** [comment]
Run this script on your site (host / sql)
https://github.com/ActiveForums/ActiveForums/blob/master/sql/05.02.04.SqlDataProvider

**Comment by frozendnn** [comment]
Hi Artfuld, 

I finally got to try the above mentioned script and the attachinsertallowed error went away but I get this error now:

ModuleDefId:110
FriendlyName:Active Forum
ModuleControlSource:DesktopModules/ActiveForums/ActiveForums.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:432002c3-1c21-473f-8338-b4714a354fdd
AssemblyVersion:7.4.0
PortalId:0
UserId:-1
TabId:64
RawUrl:/FORUMS/aft/24635
Referrer:
UserAgent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
ExceptionHash:ZtnhMieTVV1BbbzP7ZGYJA==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseContent(DataRow dr, String tempate, Int32 rowcount)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseTopic(String sOutput)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.BindTopic()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: ds000796

**Comment by frozendnn** [comment]
I am also getting this error when I try access the control panel. 

- /Forum-Settings/ctl/Edit/mid/624
Referrer:http://all4jds.com/Default.aspx?tabid=180&error=Object+reference+not+set+to+an+instance+of+an+object.
UserAgent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
ExceptionHash:uRA4fscBrdmqIvtegRJdQQ==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.ActiveForums.Controls.Callback.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by frozendnn** [comment]
What is this error and why does it come up everytime I upgrade AF on my website? Will I need to run this script every time?

**Comment by artfuld** [comment]
No you should only need to run it once and then it should be in your database.

Does it work after you ran the script or are you still having problem?

**Comment by artfuld** [comment]
If you have more problems on your site regarding AF I wouldn't mind helping you fix them, but I would need a copy of you db and site.

**Comment by johnhenley** [comment]
I also had this problem with updating from 5.2.4 to 6.1.5.
I think the problem was that the function was added to the SQL installer after 5.2.4 was actually released, so if you were upgrading from 5.2.4 you run into that error when upgrading.
Perhaps it can be added to 6.1.6 ?

**Comment by artfuld** [comment]
@johnhenley did you fix it just by running the 5.2.4-script again or did you do something else?
I will take a look at this today so it actually updates the sql for the right version

**Comment by artfuld** [comment]
Ok, I went through the versions and found a couple of strange things that I think I might have fixed. It will be in the next release.

@frozendnn please wait for @supermansrf to do the next release before you try to upgrade again.

**Comment by johnhenley** [comment]
I just ran the 5.2.4 SQL.

In a related issue, some SQL files are left in a sql folder (6.0.3 & 6.1.3) while others from prior versions in data provider folder? Any idea why? Which is correct (I think it's the provider directory)? 5.2.4 SQL was in neither folder.

John

On Mar 25, 2015, at 3:12 AM, Joakim Andersson <notifications@github.com<mailto:notifications@github.com>> wrote:


@johnhenley<https://github.com/johnhenley> did you fix it just by running the 5.2.4-script again or did you do something else?
I will take a look at this today so it actually updates the sql for the right version
