### ISSUE TITLE
Error when post or reply author is deleted

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#239]
I've been chasing my tail trying to track down a random problem I'm having on several forums.  I just figured out what causes it today.  

I cloned activeforums.org to a test site so @teambound could troubleshoot group setup.  In order to make sure we weren't replying to subscribed posts, I deleted all of the users.  Some of them had made posts/replies.  

If you look at the forumview or topicsview page, it shows deleted user as the author of the last post.  However if you click on a post, an error is generated:

DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseContent(DataRow dr, String tempate, Int32 rowcount)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseTopic(String sOutput)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.BindTopic()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
   --- End of inner exception stack trace ---

I would like to see it just work with "Deleted User" showing up instead of generating an error.  I have thousands of posts on one of my sites that have started doing this after upgrading from DNN Forums to Active Forums.  I suspected that this is why it was happening but didn't know until today.  The ONLY difference between the af test site and live site is the fact that I deleted all users permanently.

**Comment by frozendnn** [comment]
It also happens if u r allowing anonymous users to post on your website. I thought I am getting that error because my DNN upgrade went wrong. 


Sent from my Verizon Wireless 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Seth Folickman <notifications@github.com> </div><div>Date:03/14/2015  2:33 PM  (GMT-08:00) </div><div>To: ActiveForums/ActiveForums <ActiveForums@noreply.github.com> </div><div>Cc:  </div><div>Subject: [ActiveForums] Error when post or reply author is deleted (#239) </div><div>
</div>I've been chasing my tail trying to track down a random problem I'm having on several forums. I just figured out what causes it today.

I cloned activeforums.org to a test site so @teambound could troubleshoot group setup. In order to make sure we weren't replying to subscribed posts, I deleted all of the users. Some of them had made posts/replies.

If you look at the forumview or topicsview page, it shows deleted user as the author of the last post. However if you click on a post, an error is generated:

DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseContent(DataRow dr, String tempate, Int32 rowcount)
at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseTopic(String sOutput)
at DotNetNuke.Modules.ActiveForums.Controls.TopicView.BindTopic()
at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
--- End of inner exception stack trace ---

I would like to see it just work with "Deleted User" showing up instead of generating an error. I have thousands of posts on one of my sites that have started doing this after upgrading from DNN Forums to Active Forums. I suspected that this is why it was happening but didn't know until today. The ONLY difference between the af test site and live site is the fact that I deleted all users permanently.

**Comment by supermansrf** [comment]
I'm betting it doesn't have anything to do with your site at all.  I'm betting there is something in there that is relying on some property or field that doesn't exist because the user is gone.  

Its too bad there isn't any more information in the error log when this happens.  I'm betting this may be a bit hard to track down.  

@frozendnn  do you have any idea what version was the last one that allowed your anonymous users to post?

**Comment by frozendnn** [comment]
The last one I was using was 6.02 Beta, 

I directly upgraded 6.02 beta to the latest one on Friday and I cannot post any comment since then (logged in or not logged in). I cant even access the control panel. 

I get this error:

PortalId:0
UserId:57
TabId:64
RawUrl:/FORUMS/ctl/EDIT/mid/386
Referrer:http://website.com/FORUMS/afv/grid/afgt/activetopics
UserAgent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
ExceptionHash:l+PZ0QZdvgk1MataUyWuPw==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.ActiveForums.Controls.Callback.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0

**Comment by supermansrf** [comment]
Not sure if this will help or not, but have you tried to run a repair install to see if it helps?  I'm just trying to understand what's going on.  Are you saying that you were able to allow anonymous posts on 6.0.2 and basically now nothing works?  Or was the anonymous thing an issue on 6.0.2 also and the upgrade failed? 

Are you running this on a test site or live site?

**Comment by frozendnn** [comment]
unfortunately on a live site. my back up was corrupted so I am stuck trying to fix the error. My members are furious. 
Anonymous were allowed but after the upgrade nothing works. I cannot post or reply. I get the above error when I try to do it. So can't really say the issue is related to anonymous posts only.

**Comment by supermansrf** [comment]
Go look in the desktop modules/active forums/sql folder.  Look and see what sql scripts are in there (starting at 6.0.2 on) and let me know

**Comment by frozendnn** [comment]
I just reinstalled 6.1.3 and I getting the attach insert error again. 
ModuleDefId:110FriendlyName:Active ForumModuleControlSource:DesktopModules/ActiveForums/ActiveForums.ascxAbsoluteURL:/Default.aspxDefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNukeExceptionGUID:0c15a805-d6f2-441c-b136-0df1cce46646AssemblyVersion:7.4.0PortalId:0UserId:-1TabId:64RawUrl:/FORUMS/afv/post/aff/1/aft/2075/afq/2173/asg/16Referrer:UserAgent:Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)ExceptionHash:sNgkgyKyx6ISAX7TGogdug==Message:ATTACHINSERTALLOWEDStackTrace:InnerMessage:ATTACHINSERTALLOWEDInnerStackTrace:   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.LoadSettings(IDataRecord dr)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.Forums_List(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumController.GetForumsForUser(String userRoles, Int32 portalId, Int32 moduleId, String permissionType, Boolean strict)
   at DotNetNuke.Modules.ActiveForums.SettingsBase.get_UserForumsList()
   at DotNetNuke.Modules.ActiveForums.Classic.GetControl(String view, String options)Source:FileName:FileLineNumber:0FileColumnNumber:0Method:Server Name: ds000796
and 
AbsoluteURL:/Default.aspxDefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNukeExceptionGUID:a0f6b7a6-9dc6-4216-8380-78ecc9513104AssemblyVersion:7.4.0PortalId:0UserId:-1TabId:64RawUrl:/FORUMS/aft/14806Referrer:UserAgent:Mediapartners-GoogleExceptionHash:j2vIfnRZfW4jRDDbX80bFA==Message:ATTACHINSERTALLOWEDStackTrace:InnerMessage:ATTACHINSERTALLOWEDInnerStackTrace:   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.LoadSettings(IDataRecord dr)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.Forums_List(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumController.GetForumsForUser(String userRoles, Int32 portalId, Int32 moduleId, String permissionType, Boolean strict)
   at DotNetNuke.Modules.ActiveForums.SettingsBase.get_UserForumsList()
   at DotNetNuke.Modules.ActiveForums.Classic.GetControl(String view, String options)Source:FileName:FileLineNumber:0FileColumnNumber:0Method:Server Name: ds000796

and 
Message:ATTACHINSERTALLOWEDStackTrace:InnerMessage:ATTACHINSERTALLOWEDInnerStackTrace:   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.LoadSettings(IDataRecord dr)
   at DotNetNuke.Modules.ActiveForums.Data.ForumsDB.Forums_List(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumController.GetForumsForUser(String userRoles, Int32 portalId, Int32 moduleId, String permissionType, Boolean strict)
   at DotNetNuke.Modules.ActiveForums.UserController.DNNGetCurrentUser(Int32 SiteId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.UserController.GetUser(Int32 SiteId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.SettingsBase.get_ForumUser()
   at DotNetNuke.Modules.ActiveForums.Classic.SetupPage()
   at DotNetNuke.Modules.ActiveForums.Classic.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)Source:FileName:FileLineNumber:0FileColumnNumber:0

**Comment by frozendnn** [comment]
Can I upload the 6.1.4? Will that fix it?

**Comment by frozendnn** [comment]
I have 4.3.95.0.15.0.35.0.55.15.1.35.25.2.1and 6.1.3 in my sql folder

**Comment by supermansrf** [comment]
What on earth is that www.sogou.com reference in there?  That's a chinese site.  

The last few sql entries in there should be:

05.02.04
06.00.02
06.01.03

I couldn't understand what you typed, the numbers all ran together

**Comment by frozendnn** [comment]
Sorry, I replied via email. 

I have 4.3.9
5.0.1
5.0.3
5.0.5
5.1
5.1.3
5.2
5.2.1
and 6.1.3 

Dont have 6.00.02 or 5.02.04

**Comment by supermansrf** [comment]
Stupid question, but have you tried clearing site cache and restarting application?

That is strange.  You got something strange going on and I don't know enough about this to comment on it.  There are several missing that I see in every one of my sites.  The thing that throws me off is that the ones missing shouldn't have caused any issues when upgrading to 6.1.3.  They should have shown up before this if they were the problem.  

After reinstalling 6.1.3 what is the result?  Same as before?

**Comment by frozendnn** [comment]
Yes. With the attach insert error.  

However, running this script makes the error go away. https://github.com/ActiveForums/ActiveForums/issues/219#issuecomment-79397356

 But the posting issue remains. 

Right now (without running the above script) the forums throw an error and disappear.

**Comment by frozendnn** [comment]
yes, I have cleared the site cache. Would u like to see the website?

**Comment by supermansrf** [comment]
you got my email?  I'll take a look if you want.  Not sure that i can help but never know

**Comment by frozendnn** [comment]
I don't have it but I see it on your profile. :-)

**Comment by supermansrf** [comment]
I just figured out how to make it public today fire away

**Comment by artfuld** [comment]
I will take a short look at this today.

**Comment by teambound** [comment]
Have been testing group set up and found a few things that lose the groupid. I posted them as topics on the test site. I'll post on GitHub as well when I am done testing today.

**Comment by artfuld** [comment]
Ok, so there's a couple of fields that gets pulled from the user database.
Email and imgUrl is the only 2 without a "if null then".

I will post a fix for this right away.

**Comment by supermansrf** [comment]
This appears to be fixed as of 6.1.5 - I am closing this for now.  We can reopen if necessary.
