### ISSUE TITLE
What does these errors mean? 

### ISSUE THREAD

**Issue by frozendnn** [ActiveForums/ActiveForums#240]
I am using AF 6.1.3 and DNN 7.4

ModuleId:386
ModuleDefId:110
FriendlyName:Active Forum
ModuleControlSource:DesktopModules/ActiveForums/ActiveForums.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:7d0e0ca7-f069-4d54-828b-cd7db0fdba5c
AssemblyVersion:7.4.0
PortalId:0
UserId:-1
TabId:64
RawUrl:/FORUMS/aft/24636
Referrer:
UserAgent:Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)
ExceptionHash:GqS/SqTG+X8laTSdYWogVQ==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseContent(DataRow dr, String tempate, Int32 rowcount)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseTopic(String sOutput)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.BindTopic()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: ds000796
3/15/2015 2:15:30 AMPage Load Exception    AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:de7ca606-5cdd-4229-80b0-f1c26fe8e5f7
AssemblyVersion:7.4.0
PortalId:0
UserId:-1
TabId:64
RawUrl:/FORUMS/afv/post/aff/1/aft/21263/afr/82641?__redir=1
Referrer:
UserAgent:SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Browser/6.2.3.3.c.1.101 (GUI) MMP/2.0 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)
ExceptionHash:zxEsN3D8npMHy1zGLd91bg==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.ActiveForums.Controls.Callback.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: ds000796

**Comment by artfuld** [comment]
Do they show any errors in the site or is it only in the log?

**Comment by supermansrf** [comment]
@frozendnn I fell asleep on you last night.  Any progress?

**Comment by frozendnn** [comment]
@artfuld , there are the entries in the event log. 

@supermansrf , it's ok. Fortunately, I was able to revert the AF upgrade. I am running the old version now. I am planning on upgrading it to AF 6.1.5 soon. Hopefully, it works.

**Comment by artfuld** [comment]
@frozendnn did you try to update this again?
