### ISSUE TITLE
Cannot add a reply to post 

### ISSUE THREAD

**Issue by catadj** [ActiveForums/ActiveForums#311]
Active Forum version: 6.2.6
DNN Version: 7.4

Error
I'm receiving the following error when I try to add a reply to a post in the forum on my site.

Message: Invalid object name 'activeforums_Topics'.

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning()
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlDataReader.ConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.SqlDataProvider.Reply_Save(Int32 PortalId, Int32 TopicId, Int32 ReplyId, Int32 ReplyToId, Int32 StatusId, Boolean IsApproved, Boolean IsDeleted, String Subject, String Body, DateTime DateCreated, DateTime DateUpdated, Int32 AuthorId, String AuthorName, String IPAddress)
   at DotNetNuke.Modules.ActiveForums.ReplyController.Reply_Save(Int32 PortalId, ReplyInfo ri)
   at DotNetNuke.Modules.ActiveForums.af_post.SaveReply()
   at DotNetNuke.Modules.ActiveForums.af_post.ctlForm_Click(Object sender, EventArgs e)
   at DotNetNuke.Modules.ActiveForums.Controls.SubmitForm.OnBubbleClick(EventArgs e)
   at DotNetNuke.Modules.ActiveForums.Controls.SubmitForm.btnPost_Click(Object sender, EventArgs e)
   at DotNetNuke.Modules.ActiveForums.Controls.ImageButton.OnClick(EventArgs e)
   at DotNetNuke.Modules.ActiveForums.Controls.ImageButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by artfuld** [comment]
Hey,
Is this a new install or an upgrade?

**Comment by catadj** [comment]
Upgrade

**Comment by artfuld** [comment]
From what version? Do you have objectqualifier?
Den 10 aug 2015 5:02 em skrev "catadj" <notifications@github.com>:

**Comment by catadj** [comment]
Yes I do use a objectqualifier.

The prior version was 6.2.5, but I have been using Active Forums for years.    No users of the site reported having the issues with version 6.2.5 but the last time a reply was made was on 7/22/2015 which before I upgraded to 6.2.5.  I'm not sure what the version was before using 6.2.5.

**Comment by catadj** [comment]
It looks like Active Forums version prior to the 6.2.5 upgrade was 5.0.4 DNN7 Beta_4

**Comment by supermansrf** [comment]
There was something funny with that string of beta's.  All of this was on codeplex and you have to look hard to find it. 

If you used any of those betas on 5.0.4 there was an additional step that you had to manually run if you upgraded.  You should only have to run this once.  I would highly recommend backing up before running this in case my memory is way wrong and I'm guiding you down the wrong road.  It all had to do with the introduction of full text search.  

See this post here on codeplex:  https://activeforums.codeplex.com/discussions/438250

Try running that script and see what happens.  After you run it, go in and disable full text search, save, then turn it back on.  That should fix your problem.

**Comment by catadj** [comment]
Thanks,

1.  Ran the sql script and it was successful.
2. We have not been using Full text search so it had already been set to "No" or disable 
3. I tried to add a reply to a post and received the same error as before
4. I then went into the settings and turned full text search on and saved it .
5. I tried adding a reply to different topic and received the same error as first reported.

Thanks,

**Comment by catadj** [comment]
I notice that when I use the "Quick Reply" instead of the "Add Reply" I receive the following error.

The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

**Comment by artfuld** [comment]
I think that the problem lies in one stored procedure (activeforums_replies_save) and that it was missing the {databaseOwner}[{objectQualifier} when you installed.
Otherwise your error would be something like 
Message: Invalid object name 'YOURObjectQualifier_activeforums_Topics'.

Please try running this from inside dnn
[sql.txt](https://github.com/ActiveForums/ActiveForums/files/1305/sql.txt)

**Comment by catadj** [comment]
Thanks for your help.  The activeforums_topic and activeforums_Content both were missing the databaseOwner and ObjectQualifier in the " Tapatalk" section of the stored procedure.    I'm able to reply to a post using both the "Quick Reply" and "Add Reply".

This should close this issue.

Thanks again,
