### ISSUE TITLE
Clean install, unable to access control panel. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bluemanuk** [ActiveForums/ActiveForums#344]
The following error occurs after a clean install on our portal, sample portals display and navigation working but control panel is not accessible. 

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:8975c959-1235-4959-91e2-436522ebb67b
AssemblyVersion:7.4.2
PortalId:2
UserId:1
TabId:159
RawUrl:/Host/Forum/ctl/EDIT/mid/590/portalid/2
Referrer:http://icpdevelopers.biworldwide.co.uk/Host/Forum/aff/1/portalid/2
UserAgent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
ExceptionHash:p3va8JsOkipgBxtCTxNgLg==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Modules.ActiveForums.Controls.Callback.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: PP-Websv11

**Comment by sleupold** [comment]
did you install DNN in the root of an IIS website or a subfolder?

**Comment by artfuld** [comment]
Is this a child portal?
