### ISSUE TITLE
Creating a new topic in a big forum gives timeout

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#358]
Creating a new topic in a big forum gives timeout

AF 6.3.0 (updated from 4.3.8)

When I want to add a new topic in a big forum >2500 topics and > 20000 reply’s I get:
Message:Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. 

The topic is added in the forum but not in the forumsview.

Adding a topic in a not so big forum works fine. The same big forum in AF 4.3.8 works also okay.

Any idea how to fix this?

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.SqlDataProvider.Topics_SaveToForum(Int32 ForumId, Int32 TopicId, Int32 LastReplyId)
   at DotNetNuke.Modules.ActiveForums.TopicsController.Topics_SaveToForum(Int32 ForumId, Int32 TopicId, Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.af_post.SaveTopic()
   at DotNetNuke.Modules.ActiveForums.af_post.ctlForm_Click(Object sender, EventArgs e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by sleupold** [comment]
I am currently working on improvements for the SQL code and will make sure, to cover this situation.

**Comment by Plumifrons** [comment]
That’s great, can’t wait to see your improvements.

**Comment by maduranga001** [comment]
I have the same issue. Please, can you tell me if this has fixed now?

**Comment by mitchelsellers** [comment]
@sleupold did you ever come up with a fix for this issue?

**Comment by artfuld** [comment]
@Plumifrons  is this still a problem? Do you have a site where this can be tested?

**Comment by Plumifrons** [comment]
Send you a mail with the links to the test forums
