### ISSUE TITLE
AF 06.03.02 Install on DNN 8.0.4 Forum Settings

### ISSUE THREAD

**Issue by euclid-mark** [ActiveForums/ActiveForums#404]
On a fresh install of active forum 6.3.2 on DNN 8.0.4 the module has been added to a page and will not go past the initial configuration start page. All control panel functions work fine, it will just not proceed past the start page. 

![af-startpage](https://user-images.githubusercontent.com/31280189/29617705-bb6c6dac-87e3-11e7-9e54-bcc65a6dfe7b.png)

The site is configured with Gravity skin and there are no errors in the event log.

**Comment by mitchelsellers** [comment]
Is there anything in the /Portals/_default/Logs file for the current date?

**Comment by euclid-mark** [comment]
Nothing in the logs for today's date that pertain to Active Forum. The only item of interest is a repeating error message for a corrupt Lucerne index.

2017-08-23 11:08:49,592 [USB-WEB1][Thread:20][ERROR] DotNetNuke.Services.Scheduling.SchedulerClient - Lucene.Net.Index.CorruptIndexException: Unknown format version: -619970560
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory)
   at Lucene.Net.Index.IndexWriter.Init(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, Int32 maxFieldLength, IndexingChain indexingChain, IndexCommit commit)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, Analyzer a, MaxFieldLength mfl)
   at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.get_Writer()
   at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.Delete(Query query)
   at DotNetNuke.Services.Search.Internals.InternalSearchControllerImpl.DeleteSearchDocumentInternal(SearchDocument searchDocument, Boolean autoCommit)
   at DotNetNuke.Services.Search.SearchEngine.DeleteRemovedObjects()
   at DotNetNuke.Services.Search.SearchEngineScheduler.DoWork()

**Comment by artfuld** [comment]
@euclid-mark Do you still have this problem? I just did a new install of 8.0.4, installed af 6.3.2 on it and it works fine.  Closing this Issue, just reopen it if you still have problem
