### ISSUE TITLE
DNN 9.1.1 - AF 6.3.2 - Features -> HTML Input Option

### ISSUE THREAD

**Issue by JaySMa** [ActiveForums/ActiveForums#405]
Hello..
I'm changing my Forum Group settings so that the DNN Default Editor is used.  But if I change from textbox to the default editor and click on save, it doesn't save those settings.

What appears to work is that I have to open the HTML input option, select the default editor, close the HTML input option, then save for it take effect.

Also, what db table contains these settings so I can manually check this within SQL to ensure the settings are the same for all my forums instead of hitting every forum manually?

Thank you for your time and attention..

**Comment by JaySMa** [comment]
Manually made all these changes using a super user account.  Logged off and back into the website as a portal administrator and these editor changes didn't carry-over and had to manually change these settings again for this user account.

I have a number of other accounts (some admins, some forum advisors and others general users) which I have to log in as (manually moving postings over from DNN forums) and will see if these changes carry over for all accounts.

**Comment by Plumifrons** [comment]
I use a script to set my own defaults back. You can use parts of it to get your editor settings back.

DELETE FROM [dbo].[activeforums_Settings]
      WHERE  [SettingName] = 'EDITORMOBILE'
GO

INSERT INTO [dbo].[activeforums_Settings] ([ModuleId] ,[GroupKey],[SettingName] ,[SettingValue])


select [ModuleId] ,[GroupKey],'EDITORMOBILE',2 from [dbo].[activeforums_Settings]   

		   Where [SettingName] = 'EDITORTYPE' 

GO



DELETE FROM [dbo].[activeforums_Settings]
      WHERE  [SettingName] = 'ALLOWLIKES'
GO

INSERT INTO [dbo].[activeforums_Settings] ([ModuleId] ,[GroupKey],[SettingName] ,[SettingValue])


select [ModuleId] ,[GroupKey],'ALLOWLIKES','true' from [dbo].[activeforums_Settings]   

		   Where [SettingName] = 'EDITORTYPE' 

GO



UPDATE activeforums_Settings 
SET 
SettingValue = 'false'
WHERE (SettingName = 'ALLOWEMOTICONS') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = 'false'
WHERE (SettingName = 'ALLOWPOSTICON') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = 'true'
WHERE (SettingName = 'ALLOWATTACH') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = 'txt,tiff,pdf,xls,xlsx,doc,docx,ppt,pptx,jpg,png,gif,zip'
WHERE (SettingName = 'ATTACHTYPEALLOWED') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = 'true'
WHERE (SettingName = 'ALLOWHTML') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = 'true'
WHERE (SettingName = 'ATTACHALLOWBROWSESITE') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = '5'
WHERE (SettingName = 'ATTACHCOUNT') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = '6000'
WHERE (SettingName = 'ATTACHMAXHEIGHT') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = '6000'
WHERE (SettingName = 'ATTACHMAXWIDTH') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = '10000'
WHERE (SettingName = 'ATTACHMAXSIZE') 
GO

UPDATE activeforums_Settings 
SET 
SettingValue = 'true'
WHERE (SettingName = 'ALLOWLIKES') 
GO


UPDATE activeforums_Settings 
SET 
SettingValue = '0'
WHERE (SettingName = 'TOPICSTEMPLATEID') 
GO



UPDATE activeforums_Settings 
SET 
SettingValue = '27'
WHERE (SettingName = 'TOPICFORMID') 
GO




UPDATE activeforums_Settings 
SET 
SettingValue = '100%'
WHERE (SettingName = 'EDITORWIDTH') 
GO



UPDATE activeforums_Settings 
SET 
SettingValue = '250'
WHERE (SettingName = 'EDITORHEIGHT') 
GO


UPDATE activeforums_Settings 
SET 
SettingValue = '2'
WHERE (SettingName = 'EDITORTYPE') 
GO


UPDATE activeforums_Settings 
SET 
SettingValue = '2'
WHERE (SettingName = 'EDITORMOBILE') 
GO



DELETE FROM [dbo].[activeforums_Settings]
      WHERE  [SettingName] = 'ATTACHINSERTALLOWED'
GO



UPDATE activeforums_Settings 
SET 
SettingValue = 'false'
WHERE (SettingName = 'CONVERTINGTOJPEGALLOWED') 
GO

**Comment by JaySMa** [comment]
Hello..
Thank you for the posting. I ran the script you posted and ended up getting an error when I attempted to add a new posting; it's all good though since this is just a development server.

An error has occurred. Error: Active Forums is currently unavailable.

Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.Modules.ActiveForums.af_post.PrepareTopic() at DotNetNuke.Modules.ActiveForums.af_post.OnInit(EventArgs e) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.AddedControl(Control control, Int32 index) at DotNetNuke.Modules.ActiveForums.Classic.GetControl(String view, String options)

Going to roll-back to another snapshot and try it again editing out certain things, etc.

Thanks agian..

**Comment by artfuld** [comment]
Hello @JaySMa I am doing a quick lookup on this and I can see that it actually saves correct but when it shows it it goes back to defaults but only on some values.
For now I only found Permitted Users on HTML input that goes back to all users. If you know any other value please let me know.

I will try to check everything and hopefully have a fix for this week.

**Comment by supermansrf** [comment]
I have had this same issue for a while. On several settings. I can’t say which ones in particular but for example if I want a group or forum to be able to use Default DNN editor and I go make the change often times I’ll go back in and check and my change did not save. I believe there are other issues opened about this. 

Joakim I can get you on a site where this happens if you want to see what happens first hand.

**Comment by artfuld** [comment]
@supermansrf that would be perfect. I'm checking now on my developersite and found 3 settings that did not stick on group settings. I have fixed all thoose and will continue with the forum settings.

**Comment by supermansrf** [comment]
I’ll email you later tonight when I get home

**Comment by artfuld** [comment]
@supermansrf or @Plumifrons do you have a site where this happens semifrequently that I can check? Or do you have access to try the latest pr on any of your site?

**Comment by supermansrf** [comment]
Man I’m sorry for not getting back with you sooner. It’s been crazy
around here. I’m out of town this weekend and I’ll get you a test site
to look at next week.

**Comment by artfuld** [comment]
No worries, I tried to email you incase you had forgot but I'm not sure if you're still using that email. Have a great weekend, talk to you next week

**Comment by Plumifrons** [comment]
Send you a mail with the login of a new test site.

**Comment by artfuld** [comment]
Thank you @Plumifrons 

I found that these features lost value.
Groupfeatures
- Moderated, Default Trust always went back to Not Trusted
- HTML Input, Permitted Users always went back to All Users
- Auto subscriptions, New Topics Only always went back to Unchecked

Forumfeatures
- Moderated (same as groupfeatures)
- HTML input, Editor always went back to Textbox
- Auto subscriptions, (same as groupfeatures)

All the other features have been checked, and rechecked on Plumifrons site with the new pull request and it works fine.

Please let me know if you know anywhere else where the values go missing.

**Comment by Plumifrons** [comment]
It is still not always saving all the settings but its difficult to repeat it. Sometimes I can repeat it by doing the following steps.
Go to the first group settings and change the Attachments values. 
Go to the second group settings and change the Attachments values. 
Save and **Exit** the Control Panel.
When I go back to the changed settings both groups have the same old values of one of the groups.

**Comment by artfuld** [comment]
@Plumifrons ah, I have an idea where it might go wrong then. I think I've seen this behaviour on my sites aswell but I learned to always go out of the adminpanel and then back in again when working with settings, and I just forgot why and kept doing it.
I'll do some more testing

**Comment by artfuld** [comment]
Classic javascript-problem. Will hopefully have some sort of fix for this before the weekend is over and then we can release 6.3.3

**Comment by artfuld** [comment]
Ok I'm fairly positive that I have fixed this.
Steps to reproduce problem.

1. Go to Control Panel
2. Click on Forums
3. Click on any group or forum (that does not inherit group settings)
4. Go to the tab Features
5. Click Moderated On
6. Click on the ellipsis to show Moderated Settings
7. Change the values to whatever
8. Click save
9. Click back to forums
10. Click on another group or forum (that does not inherit group settings)
11. Go to the tab Features
12. If not allready click Moderated On
13. Click on the ellipsis to show Moderated Settings
The settings shown will 95% of the times be the same that you saved for the first group/forum.

Does anyone care to be my guinea pig and try my proposed fix for this?
@Plumifrons I have allready updated your test site with this fix.

**Comment by Plumifrons** [comment]
After saving the settings I get an error. The settings are saved.

AbsoluteURL:/nl-nl/DnnImageHandler.ashx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:742618b0-fa57-4121-bd65-5014e68c2ba8
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:E1PIZwYOqTloWlSAxCsQ7g==
Message:An error occurred while communicating with the remote host. The error code is 0x80070006.
StackTrace:


InnerMessage:An error occurred while communicating with the remote host. The error code is 0x80070006.
InnerStackTrace:
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.FlushCore(Boolean keepConnected, Int32 numBodyFragments, IntPtr[] bodyFragments, Int32[] bodyFragmentLengths, Int32[] bodyFragmentTypes)
   at System.Web.Hosting.IIS7WorkerRequest.FlushCachedResponse(Boolean isFinal)
   at System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders)
   at System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context, RequestNotificationStatus& status)

**Comment by artfuld** [comment]
No idea why the imagehandler crashes. I'll see if I can reproduce the error on my live site.
