### ISSUE TITLE
Did 5.2.2 break What's New Module?

### ISSUE THREAD

**Issue by frozendnn** [ActiveForums/ActiveForums#79]
Ever since (6 hours) I upgraded my forums my what's new module throws an error, My event log is bombarded with the following errors:

PortalName:website
UserID:-1
UserName:
ActiveTabID:55
ActiveTabName:HOME
RawURL:/
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:
UserAgent:Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:adf9c089-31d2-4fa1-8766-1476f4efdfef
InnerException:Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
StackTrace:
Message:
DotNetNuke.Services.Exceptions.PageLoadException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] commandParameters, SqlConnectionOwnership connectionOwnership)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.SqlDataProvider.GetPosts(Int32 PortalId, String Forums, Boolean TopicsOnly, Boolean RandomOrder, Int32 Rows, String Tags, Int32 FilterByUserId)
   at DotNetNuke.Modules.ActiveForums.WhatsNew.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---
Source:
Server Name: ds000796
3/11/2014 11:54:00 PMModule Load Exception  website  ModuleId 386 ModuleDefId 110 FriendlyName Active Forum ModuleControlSource 
ModuleId:386
ModuleDefId:110
FriendlyName:Active Forum
ModuleControlSource:DesktopModules/ActiveForums/ActiveForums.ascx
AssemblyVersion:7.2.1
PortalID:0
PortalName:website
UserID:-1
UserName:
ActiveTabID:64
ActiveTabName:FORUMS
RawURL:/FORUMS/aft/20682.aspx
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:https://www.google.com/
UserAgent:Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:4a031a3f-8e8a-46f3-927d-96d25c9ec87b
InnerException:Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
StackTrace:
Message:
DotNetNuke.Services.Exceptions.ModuleLoadException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataSet dataSet, String srcTable, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteDataset(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteDataset(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteDataset(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.SqlDataProvider.UI_TopicView(Int32 PortalId, Int32 ModuleId, Int32 ForumId, Int32 TopicId, Int32 UserId, Int32 PageIndex, Int32 PageSize, Boolean IsSuper, String Sort)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.LoadData(Int32 pageId)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
   --- End of inner exception stack trace ---
Source:
Server Name: ds000796
##

**Comment by utterlySQL** [comment]
I have since a long time back an updated version of the activeforums_TP_GetPosts proc that has been collecting dust because I haven't posted it since I wanted to do a couple of tests more.
The issue so to say with the current PROC is that it fetches allmost all posts in the databases before its just discard everything but the top number thats been specified. 
So I would advice a proper backup of the current one and perhaps this one can release some of the preasure on the database:
https://gist.github.com/utterlySQL/7918d0b95303b87700d6

**Comment by frozendnn** [comment]
@utterlySQL : Should I just run the above script via host>sql? 

How do I use it with current version? Thanks.

**Comment by utterlySQL** [comment]
@frozendnn: That is correct, if you would like to be the principal tester then update that PROC by running it via host>sql ;-) It seems to me as if the PROC hasn't been updated for a pretty long time so the latest rollback version can be found in 04.03.09.SqlDataProvider AFAIK. If you have access to SQL Management Studio I would of course advise to first script out the version of the PROC that you are running currently so its easy to rollback to if the timeout issue doesn't resolve. How many forumposts do you have, sadly my forum isn't that active so there rather little data to query from.

**Comment by frozendnn** [comment]
Total Forums	19
Total Topics	15340
Total Replies	108473
Total Members	9224
Total Active Members	39768

I have the Management studio. However, I am afraid to do anything since I am not an expert in these kind of things. Can I save the old one with a diff name and then create a new one with above code and give it the original name and try like that? How does this work?

**Comment by utterlySQL** [comment]
Yes, you could just right click and rename your current Stored Procedure activeforums_TP_GetPosts  via Management Studio. If there is a problem or not enough performance improvement with the new version then you can just rename the new one or Delete it and then rename your original activeforums_TP_GetPosts back. Pretty busy forum indeed ;-)

**Comment by frozendnn** [comment]
Thanks. Now. 

Where can I find this PROC?

**Comment by utterlySQL** [comment]
In Management Studio expand your DNN database -> Programmability -> Stored Procedures.
If it seems to be so many other Stored Procedures then you can right click Stored Procedures and choose Filter and the Name: activeforums_TP_GetPosts.
I could write a rename script of course but some environments have different {databaseOwner} than the default that usually is dbo.
So in that case the fullname including {databaseOwner} should be: dbo.activeforums_TP_GetPosts
Also note when you have renamed a PROC and then run the new version via host>sql then its rather common to just run right lick and Refresh on the Stored Procedures folder in Management Studio to actually see the changes since its no auto-refresh.

**Comment by frozendnn** [comment]
I did something wrong. 

Msg 102, Level 15, State 1, Line 2
Incorrect syntax near '{'.
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near '{'.
Msg 137, Level 15, State 2, Line 14
Must declare the scalar variable "@RandomOrder".
Msg 137, Level 15, State 2, Line 16
Must declare the scalar variable "@Rows".
Msg 319, Level 15, State 1, Line 24
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 25
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 26
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 102, Level 15, State 1, Line 28
Incorrect syntax near '}'.
Msg 137, Level 15, State 2, Line 33
Must declare the scalar variable "@RandomOrder".
Msg 137, Level 15, State 2, Line 35
Must declare the scalar variable "@Rows".
Msg 319, Level 15, State 1, Line 44
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 45
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 46
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 102, Level 15, State 1, Line 49
Incorrect syntax near '}'.
Msg 137, Level 15, State 2, Line 54
Must declare the scalar variable "@RandomOrder".
Msg 137, Level 15, State 2, Line 56
Must declare the scalar variable "@Rows".
Msg 319, Level 15, State 1, Line 66
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 67
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 68
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 69
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 102, Level 15, State 1, Line 71
Incorrect syntax near '}'.
Msg 137, Level 15, State 2, Line 76
Must declare the scalar variable "@RandomOrder".
Msg 137, Level 15, State 2, Line 79
Must declare the scalar variable "@Rows".
Msg 319, Level 15, State 1, Line 89
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 90
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 91
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Line 92
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 102, Level 15, State 1, Line 94
Incorrect syntax near '}'.

**Comment by frozendnn** [comment]
Never mind. I think it worked. I will update it you if I dont see any time out errors. Thanks for your help/
